# whitelist
branches:
  only:
    - master
services:
  #Enable docker service inside travis
  - docker
script:
  #build the image
  - bash config/buildDockerImage.sh
env:
  - $DOCKER_IMAGE_NAME="illumidesk/nginx"
